### ISSUE TITLE
Handle non JS files (e.g. .DS_Store files)

### ISSUE THREAD

**Issue by mattgi** [reach/api-framework#8]
If OSX has automatically added a .DS_Store file to a folder (does this whenever you view a folder via Finder) the App will crash 

```
/Users/matt/github/clevertech/waivecar/api/node_modules/reach-api/lib/config.js:22
      throw new Error(error);
      ^

Error: Error: ENOTDIR: not a directory, stat '/Users/matt/github/clevertech/waivecar/api/config/.DS_Store/default.js'
    at /Users/matt/github/clevertech/waivecar/api/node_modules/reach-api/lib/config.js:22:13
    at Array.forEach (native)
    at /Users/matt/github/clevertech/waivecar/api/node_modules/reach-api/lib/config.js:10:11
    at Object.<anonymous> (/Users/matt/github/clevertech/waivecar/api/node_modules/reach-api/lib/config.js:41:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
14 Sep 11:30:37 - [nodemon] app crashed - waiting for file changes before starting...
```

Need to only look at valid files in folders when looping through them.

**Comment by Kodemon** [comment]
I will fix and push update today.
